# Generated by Django 3.0.4 on 2020-03-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_keymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.DeleteModel(
            name='KeyModel',
        ),
    ]
