# Generated by Django 3.0.4 on 2020-03-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200311_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decryptmodel',
            name='file',
            field=models.FileField(upload_to='files/decrypted'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='file',
            field=models.FileField(upload_to='files/encrypted'),
        ),
    ]
