# Generated by Django 3.0.4 on 2020-03-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200311_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decryptmodel',
            old_name='file',
            new_name='encryptedFile',
        ),
    ]
